### ISSUE TITLE
SHOWING ERROR

### ISSUE THREAD

**Issue by professorberlin602** [HiDe-Techno-Tips/Blackeye-for-Windows#2]
IT SAYS THAT WINDOWS CAN'T FIND "PHP.EXE" 

PLEASE HELP!

**Comment by HiDe-Techno-Tips** [comment]
When you run it, does it show the php version as in the screenshot below.

![Untitled](https://user-images.githubusercontent.com/61367380/128908678-ed57bc7b-8bfb-42d3-a3e6-63f854669844.png)

Also, please check if a folder named `php` is located along with `blackeye.bat` or not as in the below screenshot.
That folder should have a file named `php.exe` in it along with other files.

![Untitled](https://user-images.githubusercontent.com/61367380/128909400-29aa1f72-711e-46e2-b59d-c273f25aad94.png)

**Comment by HiDe-Techno-Tips** [comment]
New version is released where this is solved.

To update, enter `40` in blackeye menu and press `y` when it ask you whether you want to check for updates or not.

This was caused because the zip file of the older version of php that is `8.0.6` being used was removed from the site.
Now php has been updated to `8.0.9`.
